# Generated by Django 5.1.3 on 2024-11-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_bfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='bcontent',
            field=models.TextField(default=''),
        ),
    ]
