# Generated by Django 5.1.3 on 2024-11-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studnts',
            new_name='Students',
        ),
    ]
